### ISSUE TITLE
Dealing with redirects/404s etc

### ISSUE THREAD

**Issue by jamesdeluk** [StevenAleong/FirefoxRandomBookmark#1]
Sometimes I get a taken to a page which no longer exists, or redirects elsewhere, etc. Ideally I'd like to remove this bookmark, but as the URL has changed, it's no longer a bookmark, and it's a hassle to hunt it down.

Is it possible to add a feature, such as an overlaid bar on the top of the window, showing the breadcrumbs for the bookmark that was opened?

**Comment by StevenAleong** [comment]
Pretty cool idea, I could update it so when you click the button and it goes to the page, use the built in firefox alert to display the path to the bookmark. 

I'll also look into some sort of overlay as another option though.

Thanks for the suggestion. Will see what I can do.

I do know there's other extensions out there that can handle broken bookmarks though

**Comment by jamesdeluk** [comment]
That would be great! Another related thought - if there's an overlay/banner etc, also have an option to edit or delete the bookmark directly. That may be more complicated to implement though.

**Comment by StevenAleong** [comment]
Hello, i just pushed an update to the plugin for v2.2.0 on firefox addons

I added to the options to keep track of the history of the last 10 randomized bookmarks, it'll show the title of the saved bookmark, path, and when you randomized it. You'll see the history in the options page.

I also updated the browser button right click option so you can see the path of the last randomized bookmark of where it is saved under the `help` menu option hover

Not QUITE what you were asking for but i think it covers what you're getting at. I thought about using the notifications banner but those don't stay forever and you might not notice.

I didn't look into editing/deleting as I don't want to stray too far from what the core of this add-on actually does and that is really just to randomize from your bookmarks.

**Comment by jamesdeluk** [comment]
That's perfect, thanks! I've just updated and it certainly helps.
