### ISSUE TITLE
I get repeated outputs after only a few tries, even with over 1000 bookmarks

### ISSUE THREAD

**Issue by OutshineIssue** [StevenAleong/FirefoxRandomBookmark#2]
Correct me if I'm wrong, but since I'm on 'Shuffled Order,' I shouldn't get repeats until I reach the last bookmark, right? The only thing that comes to mind that might be affecting the add-on's functionality is that I close the tabs as soon as I see them (I use the add-on for bookmark cleanup). Could this be the reason? If so, that's essentially my workflow with the add-on—can it be fixed?

**Comment by StevenAleong** [comment]
Definitely something isn't working correctly with the shuffled order if you're seeing repeat bookmarks before reaching the end. I'll give it a review and see what I can find and how i'm handling it.

**Comment by StevenAleong** [comment]
So I reviewed how I was handling the cached bookmark ids for keeping track of the randomize order.

Here's what it was doing before the latest version I just pushed is that if you changed the current selected group or re-selected the same group, it would re-randomize the bookmarks in that cache. It also wouldn't reset the index back to 0.

What I just pushed with v2.2.2 is that it won't re-shuffle the bookmarks for the selected group between changing of categories. It'll only re-shuffle them if the bookmarks change (added, deleted, updated).

Hopefully, with this change, it won't reshuffle the cached bookmark ids and you won't see repeats (as long as the actual bookmarks don't change).

I do use this plugin everyday but i'll switch to that `Ordered Shuffle` and keep an eye out as well but if you still notice it after updating to v2.2.2, i'm always around.

**Comment by OutshineIssue** [comment]
> It'll only re-shuffle them if the bookmarks change (added, deleted, updated).

@StevenAleong That unfortunately breaks my use case. I use the extension to clean up broken links and outdated bookmarks, so I'm constantly deleting them, which leads to a lot of repetition in my shuffles.

It would be great if a workaround could be explored for this.

**Comment by StevenAleong** [comment]
@OutshineIssue Sorry, i mean it's always reshuffled the bookmarks when they were added, updated, or deleted previously and continues to do so. 

I think if you're really looking to clean up your broken bookmarks though, it'd make more sense to use a plugin specifically for finding all your broken bookmarks i feel, i've installed bookmarks temporarily to help clean them up. 

I do get what you're trying to achieve but I guess i'm looking for what do you expect to happen when you delete or add a bookmark? 

Updating a bookmark i don't need to force a reshuffle anymore since switching from storing the urls of all the bookmarks to storing just the bookmark id and grabbing the information on the fly but previously i was storing the urls.

**Comment by OutshineIssue** [comment]
Just to clarify, I might come across broken links now and then, but it's not the core of my routine. What I actually do is open a random bookmark, check its content, and see if it's useful—no broken link detector is going to help with that. If it is, I click the extension button and keep going. If it’s not useful, I just delete the bookmark.

Ideally, it would be great to keep the same shuffle order. If I delete a bookmark, it would be awesome if it just moved on to the next one without reshuffling.

If the user really **needs** another reshuffle, maybe a button in the menu above "help" could, well, help.

**Comment by StevenAleong** [comment]
Yeah makes sense, I'll give it a review, no promises though.

**Comment by StevenAleong** [comment]
If you update the plugin to v2.2.7, you'll see a new section in the options page which will let you disable the automatic refreshing/reshuffling of bookmarks when you add/move/delete them. 

If you disable the refresh, it'll work like how you're not expecting them to.

Defaults to as it was where it would shuffle on bookmark add/move/delete.

**Comment by OutshineIssue** [comment]
That’s fantastic! I really appreciate you adding this. Thank you!
