### ISSUE TITLE
Bookmarks don't get preloaded on Firefox start

### ISSUE THREAD

**Issue by exmosis** [StevenAleong/FirefoxRandomBookmark#7]
Hi there, been using plugin a few weeks and enjoying it, so many thanks for it :) 

It has stopped working for me though. The bookmarks never get preloaded on browser start, and I just get the message "Sorry, please wait a moment while your bookmarks are preloaded. If this pop up keeps showing up after a minute, please go to the options page and scroll to the bottom and clear out all add-on data, and then reinstall the plugin. Sorry."

However, I did notice the preload code gets called when you edit a bookmark, and if I make a small change to a bookmark, then the plugin does indeed start working again.

Had a look at the code but I'm not familiar with plugin code generally, I'm afraid. I can try to install older versions though, I'm not sure if it goes back to 2.2.0.

O/S: Ubuntu 24.04.1 LTS
Browser: 133.0 (64-bit) (snap install)

**Comment by Zar-rok** [comment]
I have the same issue with the extension version `2.2.4` on Firefox `133.0` (.deb install).

However, the extension still displays the error message (“Sorry, ...”) after editing a bookmark.

A quick debugging shows that `pluginSettings.initialLoading` is always `true`.

https://github.com/StevenAleong/FirefoxRandomBookmark/blob/690d1d4170a6a55ae3c6cac3b4727fa453d07004/background.js#L43-L46

**Comment by StevenAleong** [comment]
Ah crap, I SHALL REVIEW, really sorry ya'll.

Edit: Well, i was able to replicate in my ubuntu vm so that's a start. Unable to replicate on my main windows firefox.

**Comment by StevenAleong** [comment]
Found the issue, at least in my tests for me, was that it was blowing up when i was trying to get the current theme that the user has selected, so it wouldn't continue as I assumed it'd always return a value but i guess depending on the os, it may or may not.

So like you noticed, it never got to the preloading and to hit the finish loading logic.

**Comment by StevenAleong** [comment]
Please try updating the plugin to 2.2.6 and letting me know if it works now, it worked in my tests and I hope it works for you.

**Comment by exmosis** [comment]
Aha - good find. Upgraded just now and works for me after an initial Firefox restart. Will keep an eye on it, but thanks for the quick response!

**Comment by Zar-rok** [comment]
It works for me too!

Thanks for your extension, it's really useful :)
